[project]
name = "ragforge"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.115.0",
    "langchain>=0.3.0",
    "langchain-google-genai>=2.0.0",
    "langchain-groq>=0.2.0",
    "langchain-text-splitters>=0.3.0",
    "pandas>=2.0.0",
    "pgvector>=0.3.6",
    "psycopg2-binary>=2.9.9",
    "pypdf>=5.0.0",
    "python-dotenv>=1.0.0",
    "python-multipart>=0.0.9",
    "requests>=2.32.0",
    "sqlalchemy>=2.0.35",
    "streamlit>=1.38.0",
    "uvicorn>=0.30.0",
]

[tool.pytest.ini_options]
pythonpath = ["."]

